name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t daily-energy:${{ github.sha }} ./backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag daily-energy:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/daily-energy:latest
          docker tag daily-energy:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/daily-energy:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/daily-energy:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/daily-energy:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/daily-energy:latest
            cd /root/code/daily-energy
            #            git pull origin main
            docker-compose --profile prod up -d --force-recreate