name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t daily-energy:${{ github.sha }} -f ./backend/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag daily-energy:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/daily-energy:latest
          docker tag daily-energy:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/daily-energy:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/daily-energy:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/daily-energy:${{ github.sha }}

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/daily-energy:latest
            docker-compose -f /home/ubuntu/daily-energy/docker-compose.yml --profile prod up -d